name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install poetry
        run: python -m pip install poetry

      - name: Build wheels
        run: python -m poetry build

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./dist/*.whl
  release:
    needs: [build]
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{  github.ref_name }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v} ${tag#v}" \
              --generate-notes \
              *.whl
